# DX 601 Week 11 Homework

## Introduction

In this homework, you will practice working with systems of linear equations and review previous weeks' material.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [1]:
import math
import sys

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats
import sklearn.linear_model

## Shared Data

### Vineyard Data

This data set attempts to predict yields for a small vineyard in Lake Erie in 1991 based on the yields in the previous years.
Each row of the data set represents the yields of a row of the vineyard.
See https://github.com/EpistasisLab/pmlb/blob/master/datasets/192_vineyard/metadata.yaml for more information.

In [3]:
vineyard = pd.read_csv("https://github.com/EpistasisLab/pmlb/raw/refs/heads/master/datasets/192_vineyard/192_vineyard.tsv.gz", sep="\t")
vineyard.head()

   lugs_1989  lugs_1990  target
0        1.0        5.0     9.5
1        3.0        8.0    17.5
2        3.0       11.0    18.0
3        3.0        9.0    20.0
4        5.0        9.5    20.5

In [4]:
vineyard_inputs = vineyard[["lugs_1989", "lugs_1990"]]
vineyard_inputs.head()

   lugs_1989  lugs_1990
0        1.0        5.0
1        3.0        8.0
2        3.0       11.0
3        3.0        9.0
4        5.0        9.5

In [5]:
vineyard_target = vineyard["target"]

## Problems

### Problem 1

Set `p1` to the value of $x$ after solving the following system of linear equations.

\begin{array}{rcl}
3x & = & 4.2 \\
\end{array}

In [6]:
# YOUR CHANGES HERE

p1 = 4.2/3

In [7]:
p1

1.4000000000000001

### Problem 2

Set `p2` to be a tuple of `(x, y)` where $x$ and $y$ are the solution to the following system of linear equations.

\begin{array}{rcl}
3x + 2y & = & 8.6 \\
2x + 5y & = & 13.8 \\
\end{array}

Hint: Just do this by hand.

In [8]:
# YOUR CHANGES HERE

p2 = (1.4, 2.2)

In [9]:
p2

(1.4, 2.2)

### Problem 3

Set `p3` to be the x intercept of the following equation.

\begin{array}{rcl}
4x + 2y + 3z & = & 12 \\
\end{array}

In [10]:
# YOUR CHANGES HERE
#y and z is zero
p3 = 3

In [11]:
p3

3

### Problem 4

Set `p4` to be the sum of the 5 axis intercepts of the following equation.

\begin{array}{rcl}
9a + 4b + 27c + 6d + 3e & = & 36 \\
\end{array}

In [12]:
# YOUR CHANGES HERE
a=36/9
b=36/4
c=36/27
d=36/6
e=36/3
p4 = a+b+c+d+e

In [13]:
p4

32.333333333333336

### Problem 5

Set `p5` to the augmented matrix of the following system of linear equations.

\begin{array}{rcl}
3x + 2y + 13z = 10 \\
7x + 2y - 13z = 23 \\
\end{array}

In [17]:
# YOUR CHANGES HERE

p5 = np.array([
    [3,2,13,10],
    [7,2,-13,23]
    ])

In [18]:
p5

array([[  3,   2,  13,  10],
       [  7,   2, -13,  23]])

### Problem 6

Set `p6` to the rank of the following system of linear equations?

\begin{array}{rcl}
3x + 2y + 0z = 3 \\
2x + 3y + 1z = 5 \\
5x + 5y + 5z = 20 \\
\end{array}

In [20]:
# YOUR CHANGES HERE
a=np.asarray([
    [3,2,0],
    [2,3,1],
    [5,5,5]
    ])
p6 = np.linalg.matrix_rank(a)

In [21]:
p6

np.int64(3)

### Problem 7

Consider the following system of linear equations.

\begin{array}{rcl}
3x + 2y + 0z = 3 \\
2x + 3y + 1z = 5 \\
5x + 5y + 5z = 20 \\
\end{array}

This system could be rewritten as
\begin{array}{rcl}
\mathbf{A}
\begin{bmatrix}
x \\ y \\ z \\
\end{bmatrix}
& = &
\begin{bmatrix}
3 \\ 5 \\ 20 \\
\end{bmatrix}
\end{array}

Set `p7` to $\mathbf{A}$.

In [22]:
# YOUR CHANGES HERE

p7 = np.array([[3,2,0],
               [2,3,1],
               [5,5,5]])

In [23]:
p7

array([[3, 2, 0],
       [2, 3, 1],
       [5, 5, 5]])

### Problem 8

Set `p8` to the number of free variables in the following system of linear equations.

\begin{array}{rcl}
x + 3y + 4z = 3 \\
0x + 0y + 1z = 2 \\
x + 3y + 5z = 5 \\
\end{array}

In [25]:
# YOUR CHANGES HERE
A = np.array([[1,3,4],
              [0,0,1],
              [1,3,5]])

rank_A= np.linalg.matrix_rank(A)
no_of_unknown=A.shape[1]
#rank_A
p8 = no_of_unknown-rank_A

In [26]:
p8

np.int64(1)

### Problem 9

Set `p9` to any solution `(x, y, z)` to the following system of linear equations.

\begin{array}{rcl}
2x + 4y + 0z = 16 \\
1x + 3y + 1z = 16 \\
3x + 0y + 0z = 6 \\
\end{array}

In [27]:
# YOUR CHANGES HERE
X = np.array([[2,4,0],
              [1,3,1],
              [3,0,0]])
y = np.array([16,16,6])
p9 = tuple(np.linalg.solve(X,y))

In [28]:
p9

(np.float64(2.0), np.float64(3.0), np.float64(5.0))

### Problem 10

Set `p10` to any solution `(x, y, z)` to the following system of linear equations.

\begin{array}{rcl}
x + 3y + 0z = 3 \\
0x + 0y + 1z = 2 \\
\end{array}

Hint: these equations are in reduced row echelon form, so there are shortcuts to picking solutions.

In [29]:
# YOUR CHANGES HERE

p10 = (3, 0, -1)

In [30]:
p10

(3, 0, -1)

### Problem 11

Set `p11` to be a tuple or list of the average yields in the vineyard data set for 1989, 1990, and 1991 in that order.

In [ ]:
# YOUR CHANGES HERE

p11 = ...

In [ ]:
p11

### Problem 12

Set `p12` to the 95th percentile of the data in `q12`.

In [ ]:
# DO NOT CHANGE

q12 = np.array([3.44857705, 2.09151799, 4.98803337, 3.8649001 , 1.20265499,
       3.89903439, 3.05276698, 0.92826333, 3.20371215, 1.81124845,
       3.53150155, 2.32418747, 1.81826697, 3.50670706, 1.37181554,
       2.95770001, 3.80008758, 2.65923837, 2.83248683, 2.91306525,
       2.18314379, 2.17931002, 2.9086665 , 3.26098354, 3.24755896,
       1.01129371, 4.56540725, 3.05517241, 2.32079938, 3.39392893,
       3.3886077 , 3.38112083, 3.88523072, 3.13214221, 3.73298754,
       4.11129171, 2.74133096, 2.4825709 , 3.21885293, 4.08327916,
       2.82768517, 2.1188981 , 3.45886466, 4.20440619, 2.25038228,
       1.59150786, 2.24486543, 3.49914959, 3.72254599, 1.84068517])

In [ ]:
# YOUR ANSWER HERE

p12 = ...

In [ ]:
p12

Ellipsis

### Problem 13

Set `p13` to the average $L_1$ loss using the average of 1989 and 1990 vineyard yields per row to predict 1991 yields per row.

In [ ]:
# YOUR CHANGES HERE

p13 = ...

In [ ]:
p13

### Problem 14

Build a linear regression trained with `vineyard_inputs` as its input and `vineyard_target` as its target output. Set `p14` as the output of that regression with `vineyard_inputs` as its input.

In [ ]:
# YOUR CHANGES HERE

p14 = ...

In [ ]:
p14

Ellipsis

### Problem 15

Given the following data, set `p15` to the weighted variance of

| Color | Shape | Score | Probability |
|---|---|---|---:|
| red | square | 3 | 0.250 |
| blue | circle | 4 | 0.125 |
| purple | line | 2 | 0.125 |
| purple | diamond | 5 | 0.25 |
| blue | triangle | 3 | 0.25 |

In [ ]:
# YOUR CHANGES HERE

p15 = ...

In [ ]:
p15

### Problem 16

Set `p16` to be the correlation between the 1989 and 1990 yields in the vineyard data set.

In [ ]:
# YOUR CHANGES HERE

p16 = ...

In [ ]:
p16

### Problem 17

Compute the sample mean and variance of the 1990 vineyard yields.
Assuming that the yields follow a normal distribution with your computed parameters, what would the one-sided p-value of a yield of 13 lugs be?

Hint: use the [SciPy stats module](https://docs.scipy.org/doc/scipy/reference/stats.html) to calculate the p-values from the distribution.

In [ ]:
# YOUR CHANGES HERE

p17 = ...

In [ ]:
p17

### Problem 18

Set `p18` to be the $2 \times 3$ matrix full of question marks below, filled in with the following information.
1. Each serving of noodles requires 1/2 cup of flour.
2. Each serving of noodles requires 1/8 cup of water.
3. Noodles do not need sugar.
4. Each serving of cake requires 1/4 cup of flour.
5. Each serving of cake requires 1/4 cup of sugar.
6. Cake does not need water.

\begin{array}{rcl}
\begin{bmatrix}
\text{servings of noodles} & \text{pieces of cake} \\
\end{bmatrix}
\begin{bmatrix}
\text{??} & \text{??} & \text{??} \\
\text{??} & \text{??} & \text{??} \\
\end{bmatrix}
& = &
\begin{bmatrix}
\text{flour needed} & \text{sugar needed} & \text{water needed} \\
\end{bmatrix}
\end{array}

In [ ]:
# YOUR CHANGES HERE

p18 = ...

In [ ]:
p18

### Problem 19

Set `p19` to be the cosine similarity of the vectors `x19` and `y19`.

In [ ]:
# DO NOT CHANGE

x19 = [0.4, 0.2, -0.5]
x19

[0.4, 0.2, -0.5]

In [ ]:
# DO NOT CHANGE

y19 = [-0.3, -0.2, 0.4]
y19

[-0.3, -0.2, 0.4]

In [ ]:
# YOUR CHANGES HERE

p19 = ...

In [ ]:
p19

Ellipsis

### Problem 20

Set `p20` to the reduced row echelon form of `q20`.

In [ ]:
# DO NOT CHANGE

q20 = np.array([[2., 5., -3., 2.0],
                [-2, 1, 3, -2],
                [ 4.,  1.,  0., 16.]])

In [ ]:
# YOUR CHANGES HERE

p20 = ...

In [ ]:
p20

Ellipsis

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

YOUR CHANGES HERE